nullable-getter: false
format: true
use-escaping: true
relax-syntax: true
use-named-parameters: true
# untranslated-messages-file: untranslatedMessages.txt
# synthetic-package: false
arb-dir: lib/l10n
